baseURL = "/"
languageCode = "en-us"
title = "rougon"
ignoreErrors = ["error-output-taxonomy"]

[outputs]
  page = ["json","players"]
  home = ["json", "redirect"]
  teams = ["json"]
  section = ["json"]
  taxonomy = ["json", "players"]
  term = ["json"]

[mediaTypes."text/netlify"]
suffixes = ""
delimiter = ""

[outputFormats.players]
baseName = "players"
mediatype ="application/json"
[outputFormats.redirect]
mediatype = "text/netlify"
baseName = "_redirects"
[taxonomies]
  sport = "sports"
  practice = "practices"

[permalinks]
  page = "/:section/:title/"
